
<script setup>
import { storeToRefs } from "pinia";
import axios from "axios";
import { useRoute } from "vue-router";
import { loggedUserInfo, moduleStore } from "@/stores/UserInfo";
import DynamicForm from "../../../components/Common/DynamicForm.vue";
const { GetUserInfo } = storeToRefs(loggedUserInfo());
const { GetModuleId } = storeToRefs(moduleStore());
const { SetModuleId } = moduleStore();

const route = useRoute();
</script>

<template>
  <section id="main-content" class="main-content">
    <!-- start page heading -->
    <section class="page-action">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12 padding-t_8">
            <div class="theme-primary partition-full">
              <span class="p-name text-white">Manage Lead</span>
              <span class="float-right">
                <a href="javascript:;" class="p-action-btn text-white" title="PageTour">
                  <i class="fa fa-road" aria-hidden="true"></i>
                  <br />PageTour
                </a>
              </span>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- end page heading -->
    <section class="main-content">
      <div class="container-fluid" id="divMainLeadData" v-cloak>
        <div class="border p-3">
          <Form v-slot="{ meta, validate }" ref="form">
            <div class="row">
              <div class="clearfix"></div>
              <div v-bind:class="{ 'col-lg-12 mb-3 float-left': true, 'mt-3': true }">
                <div class="heading-border">
                  <h5 class="h5">
                    <span>Comopany Information</span>
                  </h5>
                </div>
              </div>
              <DynamicForm :schema="formSchema.data" />
            </div>
            <div class="row flex-row-reverse mt-2">
              <div class="col-lg-6 text-end">
                <a
                  href="javascript:;"
                  data-tour="step: 1; title: enter DealDetail; content: AddDealDetailContent"
                  v-bind:class="{ disabled: false }"
                  v-on:click="onSubmit(meta)"
                  class="btn btn-success"
                  title="Save"
                >
                  <i class="fa fa-save pr-2"></i> Save
                </a>&nbsp;
                <a href="javascript:;" class="btn btn-danger" title="Cancel">
                  <i class="fa fa-close pr-2"></i> Cancel
                </a>
              </div>
              <div class="col-lg-6">
                <div class="py-2">
                  <!--@HtmlHelpers.MandatoryStringFull("R")-->
                </div>
              </div>
            </div>
          </Form>
        </div>
      </div>
    </section>
  </section>
</template>

<script>
export default {
  components: {
    DynamicForm,
  },
  data() {
    const formSchema = {
      data: [
        {
          display_order: 1,
          name: "client_first_name",
          label: "client_first_name",
          display_name: "FirstName",
          custom_field_id: 22,
          group_id: 2,
          group_name: "lead_contact_info",
          group_display_name: "Contact Information",
          group_is_system_generated: true,
          data_type_id: 1,
          data_type_name: "Text",
          code: "string",
          sql_type: "nvarchar",
          form_field_visibility: "YES",
          list_field_visibility: "YES",
          length: 200,
          is_required: true,
          picklist_options: null,
          decimal_places: null,
          dt_code: "text",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: "^[a-zA-Z ]*$",
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 1,
          layout_type: "triple",
          system_is_required: true,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 1,
          user_guide: "client_first_name_guide",
          cultureDetails: "[]",
          rules: null,
          astype: "input",
          inputtype: "TextField",
        },
        {
          display_order: 2,
          name: "client_last_name",
          label: "client_last_name",
          display_name: "LastName",
          custom_field_id: 23,
          group_id: 2,
          group_name: "lead_contact_info",
          group_display_name: "Contact Information",
          group_is_system_generated: true,
          data_type_id: 1,
          data_type_name: "Text",
          code: "string",
          sql_type: "nvarchar",
          form_field_visibility: "YES",
          list_field_visibility: "YES",
          length: 200,
          is_required: true,
          picklist_options: null,
          decimal_places: null,
          dt_code: "text",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: "^[a-zA-Z ]*$",
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 1,
          layout_type: "triple",
          system_is_required: true,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 1,
          user_guide: "client_last_name_guide",
          cultureDetails: "[]",
          rules: null,
          astype: "input",
          inputtype: "TextField",
        },
        {
          display_order: 3,
          name: "client_email",
          label: "client_email",
          display_name: null,
          custom_field_id: 24,
          group_id: 2,
          group_name: "lead_contact_info",
          group_display_name: "Contact Information",
          group_is_system_generated: true,
          data_type_id: 1,
          data_type_name: "Text",
          code: "string",
          sql_type: "nvarchar",
          form_field_visibility: "YES",
          list_field_visibility: "YES",
          length: 200,
          is_required: true,
          picklist_options: null,
          decimal_places: null,
          dt_code: "text",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: "email",
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 1,
          layout_type: "triple",
          system_is_required: true,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: "client_email_guide",
          cultureDetails: "[]",
          rules: "yup.string().required().email()",
          astype: "input",
          inputtype: "TextField",
        },
        {
          display_order: 4,
          name: "contact_number",
          label: "contact_number",
          display_name: "Mobile",
          custom_field_id: 30,
          group_id: 2,
          group_name: "lead_contact_info",
          group_display_name: "Contact Information",
          group_is_system_generated: true,
          data_type_id: 1,
          data_type_name: "Text",
          code: "string",
          sql_type: "nvarchar",
          form_field_visibility: "YES",
          list_field_visibility: "YES",
          length: 200,
          is_required: false,
          picklist_options: null,
          decimal_places: null,
          dt_code: "phone",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 1,
          layout_type: "triple",
          system_is_required: false,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: null,
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "input",
          inputtype: "TextField",
        },
        {
          display_order: 5,
          name: "home_phone",
          label: "home_phone",
          display_name: "Home Phone",
          custom_field_id: 51346,
          group_id: 2,
          group_name: "lead_contact_info",
          group_display_name: "Contact Information",
          group_is_system_generated: true,
          data_type_id: 1,
          data_type_name: "Text",
          code: "string",
          sql_type: "nvarchar",
          form_field_visibility: "YES",
          list_field_visibility: "YES",
          length: 200,
          is_required: false,
          picklist_options: null,
          decimal_places: null,
          dt_code: "phone",
          table_name: "talygen_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 1,
          layout_type: "triple",
          system_is_required: false,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: null,
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "input",
          inputtype: "TextField",
        },
        {
          display_order: 6,
          name: "business_phone",
          label: "business_phone",
          display_name: "Business Phone",
          custom_field_id: 51347,
          group_id: 2,
          group_name: "lead_contact_info",
          group_display_name: "Contact Information",
          group_is_system_generated: true,
          data_type_id: 1,
          data_type_name: "Text",
          code: "string",
          sql_type: "nvarchar",
          form_field_visibility: "YES",
          list_field_visibility: "YES",
          length: 200,
          is_required: false,
          picklist_options: null,
          decimal_places: null,
          dt_code: "phone",
          table_name: "talygen_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 1,
          layout_type: "triple",
          system_is_required: false,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: null,
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "input",
          inputtype: "TextField",
        },
        {
          display_order: 7,
          name: "role_title_id",
          label: "role_title_id",
          display_name: "Role Title",
          custom_field_id: 51340,
          group_id: 2,
          group_name: "lead_contact_info",
          group_display_name: "Contact Information",
          group_is_system_generated: true,
          data_type_id: 6,
          data_type_name: "Select List",
          code: "select",
          sql_type: "nvarchar",
          form_field_visibility: "YES",
          list_field_visibility: "NO",
          length: 200,
          is_required: false,
          picklist_options: "Lookup",
          decimal_places: null,
          dt_code: "select",
          table_name: "talygen_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 1,
          layout_type: "triple",
          system_is_required: false,
          field_code: "CONTACT_JOB_TITLE",
          dropdown_type: "normal",
          select_options:
            '[{"name":"Campaign","value":"187155","first_value":null,"second_value":null},{"name":"channel","value":"187082","first_value":null,"second_value":null},{"name":"Consultant","value":"187152","first_value":null,"second_value":null},{"name":"Customer","value":"187160","first_value":null,"second_value":null},{"name":"Direct","value":"187239","first_value":null,"second_value":null},{"name":"dummy","value":"186998","first_value":null,"second_value":null},{"name":"Internal Ref","value":"187083","first_value":null,"second_value":null},{"name":"Media","value":"187203","first_value":null,"second_value":null},{"name":"New Channel","value":"187097","first_value":null,"second_value":null},{"name":"News Paper","value":"187234","first_value":null,"second_value":null},{"name":"Partner","value":"187151","first_value":null,"second_value":null},{"name":"Provider","value":"187159","first_value":null,"second_value":null},{"name":"Social Media","value":"186992","first_value":null,"second_value":null},{"name":"test 12354","value":"187331","first_value":null,"second_value":null},{"name":"test lead source for CRM","value":"187334","first_value":null,"second_value":null},{"name":"test lead source for CRM 2","value":"187335","first_value":null,"second_value":null},{"name":"test5655","value":"187332","first_value":null,"second_value":null}]',
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: null,
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "select",
          inputtype: "SelectField",
        },
        {
          display_order: 8,
          name: "channel_id",
          label: "channel_id",
          display_name: "LeadSource",
          custom_field_id: 3,
          group_id: 2,
          group_name: "lead_contact_info",
          group_display_name: "Contact Information",
          group_is_system_generated: true,
          data_type_id: 6,
          data_type_name: "Select List",
          code: "select",
          sql_type: "nvarchar",
          form_field_visibility: "YES",
          list_field_visibility: "YES",
          length: 200,
          is_required: false,
          picklist_options: "Lookup",
          decimal_places: null,
          dt_code: "select",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 1,
          layout_type: "triple",
          system_is_required: false,
          field_code: "CHANNEL",
          dropdown_type: "normal",
          select_options:
            '[{"name":"Campaign","value":"187155","first_value":null,"second_value":null},{"name":"channel","value":"187082","first_value":null,"second_value":null},{"name":"Consultant","value":"187152","first_value":null,"second_value":null},{"name":"Customer","value":"187160","first_value":null,"second_value":null},{"name":"Direct","value":"187239","first_value":null,"second_value":null},{"name":"dummy","value":"186998","first_value":null,"second_value":null},{"name":"Internal Ref","value":"187083","first_value":null,"second_value":null},{"name":"Media","value":"187203","first_value":null,"second_value":null},{"name":"New Channel","value":"187097","first_value":null,"second_value":null},{"name":"News Paper","value":"187234","first_value":null,"second_value":null},{"name":"Partner","value":"187151","first_value":null,"second_value":null},{"name":"Provider","value":"187159","first_value":null,"second_value":null},{"name":"Social Media","value":"186992","first_value":null,"second_value":null},{"name":"test 12354","value":"187331","first_value":null,"second_value":null},{"name":"test lead source for CRM","value":"187334","first_value":null,"second_value":null},{"name":"test lead source for CRM 2","value":"187335","first_value":null,"second_value":null},{"name":"test5655","value":"187332","first_value":null,"second_value":null}]',
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: "channel_id_guide",
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "select",
          inputtype: "SelectField",
        },
        {
          display_order: 8,
          name: "commission_type",
          label: "commission_type",
          display_name: "CommissionType",
          custom_field_id: 51342,
          group_id: 2,
          group_name: "lead_contact_info",
          group_display_name: "Contact Information",
          group_is_system_generated: true,
          data_type_id: 1,
          data_type_name: "Text",
          code: "string",
          sql_type: "nvarchar",
          form_field_visibility: "NO",
          list_field_visibility: "NO",
          length: 200,
          is_required: false,
          picklist_options: null,
          decimal_places: null,
          dt_code: "text",
          table_name: "talygen_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 1,
          layout_type: "triple",
          system_is_required: false,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: null,
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "input",
          inputtype: "TextField",
        },
        {
          display_order: 9,
          name: "agreement_type",
          label: "agreement_type",
          display_name: "AgreementType",
          custom_field_id: 51343,
          group_id: 2,
          group_name: "lead_contact_info",
          group_display_name: "Contact Information",
          group_is_system_generated: true,
          data_type_id: 1,
          data_type_name: "Text",
          code: "string",
          sql_type: "nvarchar",
          form_field_visibility: "NO",
          list_field_visibility: "NO",
          length: 200,
          is_required: false,
          picklist_options: null,
          decimal_places: null,
          dt_code: "text",
          table_name: "talygen_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 1,
          layout_type: "triple",
          system_is_required: false,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: null,
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "input",
          inputtype: "TextField",
        },
        {
          display_order: 9,
          name: "external_source_id",
          label: "external_source_id",
          display_name: "ReferredBy",
          custom_field_id: 51341,
          group_id: 2,
          group_name: "lead_contact_info",
          group_display_name: "Contact Information",
          group_is_system_generated: true,
          data_type_id: 6,
          data_type_name: "Select List",
          code: "select",
          sql_type: "nvarchar",
          form_field_visibility: "YES",
          list_field_visibility: "NO",
          length: 200,
          is_required: false,
          picklist_options: "Lookup",
          decimal_places: null,
          dt_code: "select",
          table_name: "talygen_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 1,
          layout_type: "triple",
          system_is_required: false,
          field_code: "PARTNER_ACCOUNTS",
          dropdown_type: "normal",
          select_options:
            '[{"name":"Campaign","value":"187155","first_value":null,"second_value":null},{"name":"channel","value":"187082","first_value":null,"second_value":null},{"name":"Consultant","value":"187152","first_value":null,"second_value":null},{"name":"Customer","value":"187160","first_value":null,"second_value":null},{"name":"Direct","value":"187239","first_value":null,"second_value":null},{"name":"dummy","value":"186998","first_value":null,"second_value":null},{"name":"Internal Ref","value":"187083","first_value":null,"second_value":null},{"name":"Media","value":"187203","first_value":null,"second_value":null},{"name":"New Channel","value":"187097","first_value":null,"second_value":null},{"name":"News Paper","value":"187234","first_value":null,"second_value":null},{"name":"Partner","value":"187151","first_value":null,"second_value":null},{"name":"Provider","value":"187159","first_value":null,"second_value":null},{"name":"Social Media","value":"186992","first_value":null,"second_value":null},{"name":"test 12354","value":"187331","first_value":null,"second_value":null},{"name":"test lead source for CRM","value":"187334","first_value":null,"second_value":null},{"name":"test lead source for CRM 2","value":"187335","first_value":null,"second_value":null},{"name":"test5655","value":"187332","first_value":null,"second_value":null}]',
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: null,
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "select",
          inputtype: "SelectField",
        },
        {
          display_order: 10,
          name: "campaign_id",
          label: "campaign_id",
          display_name: "CampaignName",
          custom_field_id: 20222,
          group_id: 2,
          group_name: "lead_contact_info",
          group_display_name: "Contact Information",
          group_is_system_generated: true,
          data_type_id: 6,
          data_type_name: "Select List",
          code: "select",
          sql_type: "nvarchar",
          form_field_visibility: "YES",
          list_field_visibility: "YES",
          length: 200,
          is_required: false,
          picklist_options: "Lookup",
          decimal_places: null,
          dt_code: "select",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 1,
          layout_type: "triple",
          system_is_required: false,
          field_code: "CAMPAIGN_NAME",
          dropdown_type: "normal",
          select_options:
            '[{"name":"abc def ghi jkl mno pqrs tuv wxyz ABC DEF GHI JKL MNO PQRS TUV WXYZ !\\"§ $%& \\/() =?* \' #|; ²³~ @`´ ©«» ¤¼× {}","value":"150","first_value":null,"second_value":null},{"name":"Camp123","value":"136","first_value":null,"second_value":null},{"name":"demo test","value":"359","first_value":null,"second_value":null},{"name":"Email marketing","value":"145","first_value":null,"second_value":null},{"name":"Email marketingabc","value":"151","first_value":null,"second_value":null},{"name":"Galaxy Watch 4","value":"143","first_value":null,"second_value":null},{"name":"Galaxy Watch Launch","value":"144","first_value":null,"second_value":null},{"name":"new campain","value":"140","first_value":null,"second_value":null},{"name":"Test","value":"360","first_value":null,"second_value":null}]',
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: "campaign_id_guide",
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "select",
          inputtype: "SelectField",
        },
        {
          display_order: 1,
          name: "lead_company_name",
          label: "lead_company_name",
          display_name: "CompanyName",
          custom_field_id: 51344,
          group_id: 30140,
          group_name: "CompanyInformation",
          group_display_name: "Company Information",
          group_is_system_generated: true,
          data_type_id: 1,
          data_type_name: "Text",
          code: "string",
          sql_type: "nvarchar",
          form_field_visibility: "YES",
          list_field_visibility: "YES",
          length: 200,
          is_required: false,
          picklist_options: null,
          decimal_places: null,
          dt_code: "text",
          table_name: "talygen_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 2,
          layout_type: "triple",
          system_is_required: false,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 1,
          user_guide: null,
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "input",
          inputtype: "TextField",
        },
        {
          display_order: 2,
          name: "money_value",
          label: "money_value",
          display_name: null,
          custom_field_id: 6,
          group_id: 30140,
          group_name: "CompanyInformation",
          group_display_name: "Company Information",
          group_is_system_generated: true,
          data_type_id: 4,
          data_type_name: "Decimal",
          code: "decimal",
          sql_type: "decimal",
          form_field_visibility: "YES",
          list_field_visibility: "YES",
          length: 9,
          is_required: false,
          picklist_options: null,
          decimal_places: null,
          dt_code: "decimal",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: "^[0-9]\\d*(\\.\\d+)?$",
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 2,
          layout_type: "triple",
          system_is_required: false,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: "money_value_guide",
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "input",
          inputtype: "NumericField",
        },
        {
          display_order: 3,
          name: "industry_type_id",
          label: "industry_type_id",
          display_name: null,
          custom_field_id: 4,
          group_id: 30140,
          group_name: "CompanyInformation",
          group_display_name: "Company Information",
          group_is_system_generated: true,
          data_type_id: 6,
          data_type_name: "Select List",
          code: "select",
          sql_type: "nvarchar",
          form_field_visibility: "YES",
          list_field_visibility: "YES",
          length: 200,
          is_required: false,
          picklist_options: "Lookup",
          decimal_places: null,
          dt_code: "select",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 2,
          layout_type: "triple",
          system_is_required: false,
          field_code: "INDUSRTY_TYPE",
          dropdown_type: "normal",
          select_options:
            '[{"name":"2334","value":"12927","first_value":null,"second_value":null},{"name":"aaa","value":"12923","first_value":null,"second_value":null},{"name":"aaa","value":"13248","first_value":null,"second_value":null},{"name":"aaaa","value":"12924","first_value":null,"second_value":null},{"name":"abc","value":"12929","first_value":null,"second_value":null},{"name":"adsdfh","value":"12939","first_value":null,"second_value":null},{"name":"afda","value":"12931","first_value":null,"second_value":null},{"name":"afsdf","value":"12922","first_value":null,"second_value":null},{"name":"AkTest","value":"13296","first_value":null,"second_value":null},{"name":"asd","value":"12925","first_value":null,"second_value":null},{"name":"asdf","value":"12928","first_value":null,"second_value":null},{"name":"asdf","value":"12932","first_value":null,"second_value":null},{"name":"asdf","value":"13051","first_value":null,"second_value":null},{"name":"asdf","value":"12941","first_value":null,"second_value":null},{"name":"asdf","value":"12949","first_value":null,"second_value":null},{"name":"asdf","value":"12992","first_value":null,"second_value":null},{"name":"asdsa","value":"12921","first_value":null,"second_value":null},{"name":"dsfasdf","value":"12938","first_value":null,"second_value":null},{"name":"dsfsdfgds","value":"12940","first_value":null,"second_value":null},{"name":"eryer","value":"13224","first_value":null,"second_value":null},{"name":"ey","value":"13229","first_value":null,"second_value":null},{"name":"fghgh","value":"13260","first_value":null,"second_value":null},{"name":"gfrdfgffffffrdfbhfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfg","value":"13251","first_value":null,"second_value":null},{"name":"Government","value":"12914","first_value":null,"second_value":null},{"name":"Government2","value":"13247","first_value":null,"second_value":null},{"name":"Grand","value":"13250","first_value":null,"second_value":null},{"name":"Industry new","value":"12917","first_value":null,"second_value":null},{"name":"IT & Computers","value":"13221","first_value":null,"second_value":null},{"name":"Mac Industry","value":"12918","first_value":null,"second_value":null},{"name":"Medium Enterprise","value":"12915","first_value":null,"second_value":null},{"name":"New Job IT","value":"13259","first_value":null,"second_value":null},{"name":"night","value":"12936","first_value":null,"second_value":null},{"name":"pppppp","value":"13290","first_value":null,"second_value":null},{"name":"Private","value":"12916","first_value":null,"second_value":null},{"name":"ReInsurance","value":"12919","first_value":null,"second_value":null},{"name":"S maan","value":"12935","first_value":null,"second_value":null},{"name":"sdf","value":"12926","first_value":null,"second_value":null},{"name":"sdsf","value":"13232","first_value":null,"second_value":null},{"name":"Service Provider","value":"12913","first_value":null,"second_value":null},{"name":"Software Services","value":"13222","first_value":null,"second_value":null},{"name":"sss","value":"13226","first_value":null,"second_value":null},{"name":"ssss","value":"12937","first_value":null,"second_value":null},{"name":"tesr","value":"13289","first_value":null,"second_value":null},{"name":"test","value":"13308","first_value":null,"second_value":null},{"name":"test","value":"13286","first_value":null,"second_value":null},{"name":"test","value":"13287","first_value":null,"second_value":null},{"name":"test","value":"13288","first_value":null,"second_value":null},{"name":"Test","value":"13049","first_value":null,"second_value":null},{"name":"Test Functional area","value":"13245","first_value":null,"second_value":null},{"name":"Test Functional Area","value":"13246","first_value":null,"second_value":null},{"name":"test industry for CRM","value":"13310","first_value":null,"second_value":null},{"name":"test industry for CRM 2","value":"13311","first_value":null,"second_value":null},{"name":"test industry for CRM 3","value":"13312","first_value":null,"second_value":null},{"name":"test industry for CRM 4","value":"13313","first_value":null,"second_value":null},{"name":"Test Test","value":"13225","first_value":null,"second_value":null},{"name":"Test Testert","value":"13228","first_value":null,"second_value":null},{"name":"Test Testyhu","value":"13230","first_value":null,"second_value":null},{"name":"Test1","value":"13050","first_value":null,"second_value":null},{"name":"test141","value":"13199","first_value":null,"second_value":null},{"name":"test234","value":"13227","first_value":null,"second_value":null},{"name":"test32","value":"13233","first_value":null,"second_value":null},{"name":"Test324","value":"13234","first_value":null,"second_value":null},{"name":"Test3243","value":"13235","first_value":null,"second_value":null},{"name":"Test32455","value":"13236","first_value":null,"second_value":null},{"name":"Test324890","value":"13237","first_value":null,"second_value":null},{"name":"Test44","value":"13319","first_value":null,"second_value":null},{"name":"Test77","value":"13223","first_value":null,"second_value":null},{"name":"Test88","value":"13231","first_value":null,"second_value":null},{"name":"TestfuncionalArea","value":"13249","first_value":null,"second_value":null},{"name":"vccc","value":"12920","first_value":null,"second_value":null},{"name":"xyss","value":"12934","first_value":null,"second_value":null},{"name":"xyx","value":"12933","first_value":null,"second_value":null},{"name":"xyz","value":"12930","first_value":null,"second_value":null}]',
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: null,
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "select",
          inputtype: "SelectField",
        },
        {
          display_order: 1,
          name: "lead_address1",
          label: "lead_address1",
          display_name: "Address1",
          custom_field_id: 51337,
          group_id: 30139,
          group_name: "AddressInformation",
          group_display_name: "Address Information",
          group_is_system_generated: true,
          data_type_id: 1,
          data_type_name: "Text",
          code: "string",
          sql_type: "nvarchar",
          form_field_visibility: "YES",
          list_field_visibility: "NO",
          length: 200,
          is_required: false,
          picklist_options: null,
          decimal_places: null,
          dt_code: "text",
          table_name: "talygen_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 3,
          layout_type: "triple",
          system_is_required: false,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 1,
          user_guide: null,
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "input",
          inputtype: "TextField",
        },
        {
          display_order: 2,
          name: "lead_address2",
          label: "lead_address2",
          display_name: "Address2",
          custom_field_id: 51338,
          group_id: 30139,
          group_name: "AddressInformation",
          group_display_name: "Address Information",
          group_is_system_generated: true,
          data_type_id: 1,
          data_type_name: "Text",
          code: "string",
          sql_type: "nvarchar",
          form_field_visibility: "YES",
          list_field_visibility: "NO",
          length: 200,
          is_required: false,
          picklist_options: null,
          decimal_places: null,
          dt_code: "text",
          table_name: "talygen_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 3,
          layout_type: "triple",
          system_is_required: false,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: null,
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "input",
          inputtype: "TextField",
        },
        {
          display_order: 3,
          name: "lead_city",
          label: "lead_city",
          display_name: "City",
          custom_field_id: 51336,
          group_id: 30139,
          group_name: "AddressInformation",
          group_display_name: "Address Information",
          group_is_system_generated: true,
          data_type_id: 1,
          data_type_name: "Text",
          code: "string",
          sql_type: "nvarchar",
          form_field_visibility: "YES",
          list_field_visibility: "YES",
          length: 200,
          is_required: false,
          picklist_options: null,
          decimal_places: null,
          dt_code: "text",
          table_name: "talygen_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 3,
          layout_type: "triple",
          system_is_required: false,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 1,
          user_guide: null,
          cultureDetails:
            '[{"localization_id":20379,"custom_field_id":51336,"lang_id":1,"localization_value":null,"user_guide":null}]',
          rules: "yup.string().required()",
          astype: "input",
          inputtype: "TextField",
        },
        {
          display_order: 4,
          name: "lead_state",
          label: "lead_state",
          display_name: "State",
          custom_field_id: 51335,
          group_id: 30139,
          group_name: "AddressInformation",
          group_display_name: "Address Information",
          group_is_system_generated: true,
          data_type_id: 6,
          data_type_name: "Select List",
          code: "select",
          sql_type: "nvarchar",
          form_field_visibility: "YES",
          list_field_visibility: "YES",
          length: 200,
          is_required: false,
          picklist_options: "Lookup",
          decimal_places: null,
          dt_code: "select",
          table_name: "talygen_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 3,
          layout_type: "triple",
          system_is_required: false,
          field_code: "STATE",
          dropdown_type: "normal",
          select_options:
            '[{"name":"Campaign","value":"187155","first_value":null,"second_value":null},{"name":"channel","value":"187082","first_value":null,"second_value":null},{"name":"Consultant","value":"187152","first_value":null,"second_value":null},{"name":"Customer","value":"187160","first_value":null,"second_value":null},{"name":"Direct","value":"187239","first_value":null,"second_value":null},{"name":"dummy","value":"186998","first_value":null,"second_value":null},{"name":"Internal Ref","value":"187083","first_value":null,"second_value":null},{"name":"Media","value":"187203","first_value":null,"second_value":null},{"name":"New Channel","value":"187097","first_value":null,"second_value":null},{"name":"News Paper","value":"187234","first_value":null,"second_value":null},{"name":"Partner","value":"187151","first_value":null,"second_value":null},{"name":"Provider","value":"187159","first_value":null,"second_value":null},{"name":"Social Media","value":"186992","first_value":null,"second_value":null},{"name":"test 12354","value":"187331","first_value":null,"second_value":null},{"name":"test lead source for CRM","value":"187334","first_value":null,"second_value":null},{"name":"test lead source for CRM 2","value":"187335","first_value":null,"second_value":null},{"name":"test5655","value":"187332","first_value":null,"second_value":null}]',
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 1,
          user_guide: null,
          cultureDetails:
            '[{"localization_id":20378,"custom_field_id":51335,"lang_id":1,"localization_value":null,"user_guide":null}]',
          rules: "yup.string().required()",
          astype: "select",
          inputtype: "SelectField",
        },
        {
          display_order: 5,
          name: "lead_zipcode",
          label: "lead_zipcode",
          display_name: "ZipCode",
          custom_field_id: 51339,
          group_id: 30139,
          group_name: "AddressInformation",
          group_display_name: "Address Information",
          group_is_system_generated: true,
          data_type_id: 1,
          data_type_name: "Text",
          code: "string",
          sql_type: "nvarchar",
          form_field_visibility: "YES",
          list_field_visibility: "NO",
          length: 200,
          is_required: false,
          picklist_options: null,
          decimal_places: null,
          dt_code: "text",
          table_name: "talygen_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 3,
          layout_type: "triple",
          system_is_required: false,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 1,
          user_guide: null,
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "input",
          inputtype: "TextField",
        },
        {
          display_order: 6,
          name: "lead_country",
          label: "lead_country",
          display_name: "Country",
          custom_field_id: 51334,
          group_id: 30139,
          group_name: "AddressInformation",
          group_display_name: "Address Information",
          group_is_system_generated: true,
          data_type_id: 6,
          data_type_name: "Select List",
          code: "select",
          sql_type: "nvarchar",
          form_field_visibility: "YES",
          list_field_visibility: "YES",
          length: 200,
          is_required: false,
          picklist_options: "Lookup",
          decimal_places: null,
          dt_code: "select",
          table_name: "talygen_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 3,
          layout_type: "triple",
          system_is_required: false,
          field_code: "COUNTRIES",
          dropdown_type: "normal",
          select_options:
            '[{"name":"Campaign","value":"187155","first_value":null,"second_value":null},{"name":"channel","value":"187082","first_value":null,"second_value":null},{"name":"Consultant","value":"187152","first_value":null,"second_value":null},{"name":"Customer","value":"187160","first_value":null,"second_value":null},{"name":"Direct","value":"187239","first_value":null,"second_value":null},{"name":"dummy","value":"186998","first_value":null,"second_value":null},{"name":"Internal Ref","value":"187083","first_value":null,"second_value":null},{"name":"Media","value":"187203","first_value":null,"second_value":null},{"name":"New Channel","value":"187097","first_value":null,"second_value":null},{"name":"News Paper","value":"187234","first_value":null,"second_value":null},{"name":"Partner","value":"187151","first_value":null,"second_value":null},{"name":"Provider","value":"187159","first_value":null,"second_value":null},{"name":"Social Media","value":"186992","first_value":null,"second_value":null},{"name":"test 12354","value":"187331","first_value":null,"second_value":null},{"name":"test lead source for CRM","value":"187334","first_value":null,"second_value":null},{"name":"test lead source for CRM 2","value":"187335","first_value":null,"second_value":null},{"name":"test5655","value":"187332","first_value":null,"second_value":null}]',
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: null,
          cultureDetails:
            '[{"localization_id":20375,"custom_field_id":51334,"lang_id":1,"localization_value":null,"user_guide":null}]',
          rules: "yup.string().required()",
          astype: "select",
          inputtype: "SelectField",
        },
        {
          display_order: 1,
          name: "lead_owner_id",
          label: "lead_owner_id",
          display_name: "LeadOwner",
          custom_field_id: 1,
          group_id: 1,
          group_name: "lead_details",
          group_display_name: "Lead Information",
          group_is_system_generated: true,
          data_type_id: 6,
          data_type_name: "Select List",
          code: "select",
          sql_type: "nvarchar",
          form_field_visibility: "YES",
          list_field_visibility: "YES",
          length: 200,
          is_required: true,
          picklist_options: "Lookup",
          decimal_places: null,
          dt_code: "select",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 4,
          layout_type: "triple",
          system_is_required: true,
          field_code: "CRM_USERS",
          dropdown_type: "custom",
          select_options: "",
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 1,
          user_guide: "lead_owner_id_guide",
          cultureDetails: "[]",
          rules: null,
          astype: "select",
          inputtype: "SelectField",
        },
        {
          display_order: 2,
          name: "lead_date",
          label: "lead_date",
          display_name: null,
          custom_field_id: 20,
          group_id: 1,
          group_name: "lead_details",
          group_display_name: "Lead Information",
          group_is_system_generated: true,
          data_type_id: 5,
          data_type_name: "Date",
          code: "date",
          sql_type: "datetime",
          form_field_visibility: "YES",
          list_field_visibility: "YES",
          length: 12,
          is_required: true,
          picklist_options: null,
          decimal_places: null,
          dt_code: "date",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 4,
          layout_type: "triple",
          system_is_required: true,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: "lead_date_guide",
          cultureDetails: "[]",
          rules: null,
          astype: "input",
          inputtype: "DateField",
        },
        {
          display_order: 2,
          name: "company_id",
          label: "company_id",
          display_name: "CompanyName",
          custom_field_id: 2,
          group_id: 1,
          group_name: "lead_details",
          group_display_name: "Lead Information",
          group_is_system_generated: true,
          data_type_id: 3,
          data_type_name: "Long Integer",
          code: "bigint",
          sql_type: "decimal",
          form_field_visibility: "NO",
          list_field_visibility: "NO",
          length: 8,
          is_required: true,
          picklist_options: null,
          decimal_places: null,
          dt_code: "bigint",
          table_name: "TALYGEN_crm_lead",
          value: "270936",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 4,
          layout_type: "triple",
          system_is_required: true,
          field_code: "CRM_COMPANY",
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: null,
          cultureDetails: "[]",
          rules: null,
          astype: "input",
          inputtype: "NumericField",
        },
        {
          display_order: 3,
          name: "expected_close_date",
          label: "expected_close_date",
          display_name: null,
          custom_field_id: 5,
          group_id: 1,
          group_name: "lead_details",
          group_display_name: "Lead Information",
          group_is_system_generated: true,
          data_type_id: 5,
          data_type_name: "Date",
          code: "date",
          sql_type: "datetime",
          form_field_visibility: "YES",
          list_field_visibility: "YES",
          length: 12,
          is_required: false,
          picklist_options: null,
          decimal_places: null,
          dt_code: "date",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 4,
          layout_type: "triple",
          system_is_required: false,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: "expected_close_date_guide",
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "input",
          inputtype: "DateField",
        },
        {
          display_order: 4,
          name: "status_id",
          label: "status_id",
          display_name: "Status",
          custom_field_id: 18,
          group_id: 1,
          group_name: "lead_details",
          group_display_name: "Lead Information",
          group_is_system_generated: true,
          data_type_id: 6,
          data_type_name: "Select List",
          code: "select",
          sql_type: "nvarchar",
          form_field_visibility: "YES",
          list_field_visibility: "YES",
          length: 200,
          is_required: true,
          picklist_options: "Lookup",
          decimal_places: null,
          dt_code: "select",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 4,
          layout_type: "triple",
          system_is_required: true,
          field_code: "LEAD_DEAL_STATUS",
          dropdown_type: "normal",
          select_options:
            '[{"name":"Active","value":"1001","first_value":null,"second_value":null},{"name":"Cancelled","value":"81342","first_value":null,"second_value":null},{"name":"Closed","value":"51142","first_value":null,"second_value":null},{"name":"Inactive","value":"1002","first_value":null,"second_value":null},{"name":"InProgress","value":"91433","first_value":null,"second_value":null},{"name":"Negotiation","value":"91429","first_value":null,"second_value":null}]',
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: "status_id_guide",
          cultureDetails: "[]",
          rules: null,
          astype: "select",
          inputtype: "SelectField",
        },
        {
          display_order: 5,
          name: "existing_client_id",
          label: "existing_client_id",
          display_name: "client",
          custom_field_id: 10,
          group_id: 1,
          group_name: "lead_details",
          group_display_name: "Lead Information",
          group_is_system_generated: true,
          data_type_id: 6,
          data_type_name: "Select List",
          code: "select",
          sql_type: "nvarchar",
          form_field_visibility: "NO",
          list_field_visibility: "NO",
          length: 200,
          is_required: true,
          picklist_options: "Lookup",
          decimal_places: null,
          dt_code: "select",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 4,
          layout_type: "triple",
          system_is_required: true,
          field_code: "CLIENT",
          dropdown_type: "custom",
          select_options: "",
          parent_id: 9,
          dependent_type: "show",
          dependent_show_type: 0,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: null,
          cultureDetails: "[]",
          rules: null,
          astype: "select",
          inputtype: "SelectField",
        },
        {
          display_order: 5,
          name: "is_existing_client",
          label: "is_existing_client",
          display_name: "IsExistingClient",
          custom_field_id: 9,
          group_id: 1,
          group_name: "lead_details",
          group_display_name: "Lead Information",
          group_is_system_generated: true,
          data_type_id: 1,
          data_type_name: "Text",
          code: "string",
          sql_type: "nvarchar",
          form_field_visibility: "NO",
          list_field_visibility: "NO",
          length: 10,
          is_required: false,
          picklist_options: "Yes",
          decimal_places: null,
          dt_code: "radio",
          table_name: "TALYGEN_crm_lead",
          value: "0",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 4,
          layout_type: "triple",
          system_is_required: false,
          field_code: null,
          dropdown_type: null,
          select_options: "",
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 1,
          is_email_template: 0,
          user_guide: "is_existing_client_guide",
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "input",
          inputtype: "radio",
        },
        {
          display_order: 7,
          name: "percentage_close",
          label: "percentage_close",
          display_name: null,
          custom_field_id: 8,
          group_id: 1,
          group_name: "lead_details",
          group_display_name: "Lead Information",
          group_is_system_generated: true,
          data_type_id: 4,
          data_type_name: "Decimal",
          code: "decimal",
          sql_type: "decimal",
          form_field_visibility: "NO",
          list_field_visibility: "NO",
          length: 9,
          is_required: false,
          picklist_options: null,
          decimal_places: null,
          dt_code: "decimal",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 4,
          layout_type: "triple",
          system_is_required: false,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: "percentage_close_guide",
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "input",
          inputtype: "NumericField",
        },
        {
          display_order: 10,
          name: "project_id",
          label: "project_id",
          display_name: "ProjectName",
          custom_field_id: 11,
          group_id: 1,
          group_name: "lead_details",
          group_display_name: "Lead Information",
          group_is_system_generated: true,
          data_type_id: 3,
          data_type_name: "Long Integer",
          code: "bigint",
          sql_type: "decimal",
          form_field_visibility: "NO",
          list_field_visibility: "NO",
          length: 8,
          is_required: false,
          picklist_options: null,
          decimal_places: null,
          dt_code: "bigint",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 4,
          layout_type: "triple",
          system_is_required: false,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: null,
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "input",
          inputtype: "NumericField",
        },
        {
          display_order: 11,
          name: "created_at",
          label: "created_at",
          display_name: null,
          custom_field_id: 12,
          group_id: 1,
          group_name: "lead_details",
          group_display_name: "Lead Information",
          group_is_system_generated: true,
          data_type_id: 5,
          data_type_name: "Date",
          code: "date",
          sql_type: "datetime",
          form_field_visibility: "NO",
          list_field_visibility: "YES",
          length: 12,
          is_required: false,
          picklist_options: null,
          decimal_places: null,
          dt_code: "date",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 4,
          layout_type: "triple",
          system_is_required: false,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: null,
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "input",
          inputtype: "DateField",
        },
        {
          display_order: 12,
          name: "created_by",
          label: "created_by",
          display_name: "CreatedBy",
          custom_field_id: 13,
          group_id: 1,
          group_name: "lead_details",
          group_display_name: "Lead Information",
          group_is_system_generated: true,
          data_type_id: 6,
          data_type_name: "Select List",
          code: "select",
          sql_type: "nvarchar",
          form_field_visibility: "NO",
          list_field_visibility: "YES",
          length: 8,
          is_required: false,
          picklist_options: null,
          decimal_places: null,
          dt_code: "text",
          table_name: "TALYGEN_crm_lead",
          value: "769083",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 4,
          layout_type: "triple",
          system_is_required: false,
          field_code: "CRM_USERS",
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: null,
          cultureDetails:
            '[{"localization_id":20369,"custom_field_id":13,"lang_id":1,"localization_value":null,"user_guide":null}]',
          rules: "yup.string().required()",
          astype: "input",
          inputtype: "TextField",
        },
        {
          display_order: 13,
          name: "modified_at",
          label: "modified_at",
          display_name: "LastModifyDate",
          custom_field_id: 14,
          group_id: 1,
          group_name: "lead_details",
          group_display_name: "Lead Information",
          group_is_system_generated: true,
          data_type_id: 5,
          data_type_name: "Date",
          code: "date",
          sql_type: "datetime",
          form_field_visibility: "NO",
          list_field_visibility: "YES",
          length: 12,
          is_required: false,
          picklist_options: null,
          decimal_places: null,
          dt_code: "date",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 4,
          layout_type: "triple",
          system_is_required: false,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: null,
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "input",
          inputtype: "DateField",
        },
        {
          display_order: 14,
          name: "modified_by",
          label: "modified_by",
          display_name: "ModifiedBy",
          custom_field_id: 15,
          group_id: 1,
          group_name: "lead_details",
          group_display_name: "Lead Information",
          group_is_system_generated: true,
          data_type_id: 6,
          data_type_name: "Select List",
          code: "select",
          sql_type: "nvarchar",
          form_field_visibility: "NO",
          list_field_visibility: "YES",
          length: 8,
          is_required: false,
          picklist_options: null,
          decimal_places: null,
          dt_code: "bigint",
          table_name: "TALYGEN_crm_lead",
          value: "769083",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 4,
          layout_type: "triple",
          system_is_required: false,
          field_code: "CRM_USERS",
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: null,
          cultureDetails:
            '[{"localization_id":20377,"custom_field_id":15,"lang_id":1,"localization_value":null,"user_guide":null}]',
          rules: "yup.string().required()",
          astype: "input",
          inputtype: "NumericField",
        },
        {
          display_order: 16,
          name: "project_name",
          label: "project_name",
          display_name: "ProjectName",
          custom_field_id: 19,
          group_id: 1,
          group_name: "lead_details",
          group_display_name: "Lead Information",
          group_is_system_generated: true,
          data_type_id: 1,
          data_type_name: "Text",
          code: "string",
          sql_type: "nvarchar",
          form_field_visibility: "NO",
          list_field_visibility: "NO",
          length: 200,
          is_required: false,
          picklist_options: null,
          decimal_places: null,
          dt_code: "text",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 4,
          layout_type: "triple",
          system_is_required: false,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: null,
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "input",
          inputtype: "TextField",
        },
        {
          display_order: 22,
          name: "crm_type",
          label: "crm_type",
          display_name: null,
          custom_field_id: 25,
          group_id: 1,
          group_name: "lead_details",
          group_display_name: "Lead Information",
          group_is_system_generated: true,
          data_type_id: 1,
          data_type_name: "Text",
          code: "string",
          sql_type: "nvarchar",
          form_field_visibility: "NO",
          list_field_visibility: "NO",
          length: 10,
          is_required: true,
          picklist_options: null,
          decimal_places: null,
          dt_code: "text",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 4,
          layout_type: "triple",
          system_is_required: true,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: "crm_type_guide",
          cultureDetails: "[]",
          rules: null,
          astype: "input",
          inputtype: "TextField",
        },
        {
          display_order: 23,
          name: "ref_source_id",
          label: "ref_source_id",
          display_name: "ref_source_id",
          custom_field_id: 27,
          group_id: 1,
          group_name: "lead_details",
          group_display_name: "Lead Information",
          group_is_system_generated: true,
          data_type_id: 2,
          data_type_name: "Integer",
          code: "int",
          sql_type: "int",
          form_field_visibility: "NO",
          list_field_visibility: "NO",
          length: 4,
          is_required: false,
          picklist_options: null,
          decimal_places: null,
          dt_code: "int",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 4,
          layout_type: "triple",
          system_is_required: false,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: "ref_source_id_guide",
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "input",
          inputtype: "NumericField",
        },
        {
          display_order: 24,
          name: "ref_source_name",
          label: "ref_source_name",
          display_name: "ref_source_name",
          custom_field_id: 28,
          group_id: 1,
          group_name: "lead_details",
          group_display_name: "Lead Information",
          group_is_system_generated: true,
          data_type_id: 1,
          data_type_name: "Text",
          code: "string",
          sql_type: "nvarchar",
          form_field_visibility: "NO",
          list_field_visibility: "NO",
          length: 200,
          is_required: false,
          picklist_options: null,
          decimal_places: null,
          dt_code: "text",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 4,
          layout_type: "triple",
          system_is_required: false,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: "ref_source_name_guide",
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "input",
          inputtype: "TextField",
        },
        {
          display_order: 25,
          name: "crm_ref_id",
          label: "crm_ref_id",
          display_name: "crm_ref_id",
          custom_field_id: 29,
          group_id: 1,
          group_name: "lead_details",
          group_display_name: "Lead Information",
          group_is_system_generated: true,
          data_type_id: 1,
          data_type_name: "Text",
          code: "string",
          sql_type: "nvarchar",
          form_field_visibility: "NO",
          list_field_visibility: "NO",
          length: 200,
          is_required: false,
          picklist_options: null,
          decimal_places: null,
          dt_code: "text",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 4,
          layout_type: "triple",
          system_is_required: false,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: "crm_ref_id_guide",
          cultureDetails: "[]",
          rules: "yup.string().required()",
          astype: "input",
          inputtype: "TextField",
        },
        {
          display_order: 28,
          name: "lead_id",
          label: "lead_id",
          display_name: null,
          custom_field_id: 20173,
          group_id: 1,
          group_name: "lead_details",
          group_display_name: "Lead Information",
          group_is_system_generated: true,
          data_type_id: 3,
          data_type_name: "Long Integer",
          code: "bigint",
          sql_type: "decimal",
          form_field_visibility: "NO",
          list_field_visibility: "NO",
          length: 8,
          is_required: true,
          picklist_options: null,
          decimal_places: null,
          dt_code: "bigint",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 4,
          layout_type: "triple",
          system_is_required: true,
          field_code: null,
          dropdown_type: null,
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: null,
          cultureDetails: "[]",
          rules: null,
          astype: "input",
          inputtype: "NumericField",
        },
        {
          display_order: 30,
          name: "account_id",
          label: "account_id",
          display_name: null,
          custom_field_id: 30591,
          group_id: 1,
          group_name: "lead_details",
          group_display_name: "Lead Information",
          group_is_system_generated: true,
          data_type_id: 6,
          data_type_name: "Select List",
          code: "select",
          sql_type: "nvarchar",
          form_field_visibility: "NO",
          list_field_visibility: "YES",
          length: 200,
          is_required: true,
          picklist_options: null,
          decimal_places: null,
          dt_code: "select",
          table_name: "TALYGEN_crm_lead",
          value: "",
          select_value: "",
          validation_type: null,
          range_from: null,
          range_to: null,
          regular_expression: null,
          is_updated: 0,
          is_inserted: 0,
          is_include_in_post_jon: "yes",
          is_system_generated: true,
          group_display_order: 4,
          layout_type: "triple",
          system_is_required: true,
          field_code: "ACCOUNTS",
          dropdown_type: "custom",
          select_options: null,
          parent_id: null,
          dependent_type: null,
          dependent_show_type: 1,
          has_dependent: 0,
          is_email_template: 0,
          user_guide: "account_id_guide",
          cultureDetails:
            '[{"localization_id":20376,"custom_field_id":30591,"lang_id":1,"localization_value":null,"user_guide":null}]',
          rules: null,
          astype: "select",
          inputtype: "SelectField",
        },
      ],
      languages: [
        {
          lang_name: "English",
          lang_id: 1,
        },
        {
          lang_name: "Español",
          lang_id: 2,
        },
        {
          lang_name: "Português",
          lang_id: 3,
        },
        {
          lang_name: "Deutsch",
          lang_id: 4,
        },
        {
          lang_name: "Français",
          lang_id: 5,
        },
        {
          lang_name: "русский(Russian)",
          lang_id: 6,
        },
        {
          lang_name: "中文(Chinese)",
          lang_id: 7,
        },
        {
          lang_name: "한국의(Korean)",
          lang_id: 8,
        },
        {
          lang_name: "ελληνικά(Greek)",
          lang_id: 9,
        },
        {
          lang_name: "Italiano",
          lang_id: 11,
        },
        {
          lang_name: "Nederlands",
          lang_id: 12,
        },
        {
          lang_name: "Polski",
          lang_id: 13,
        },
        {
          lang_name: "Türkçe",
          lang_id: 14,
        },
        {
          lang_name: "Українська(ukrianian)",
          lang_id: 15,
        },
        {
          lang_name: "العربية(Saudi Arabia)",
          lang_id: 16,
        },
        {
          lang_name: "日本の(Japanese)",
          lang_id: 10018,
        },
        {
          lang_name: "Hungarian",
          lang_id: 10019,
        },
        {
          lang_name: "Indonesian",
          lang_id: 10020,
        },
        {
          lang_name: "Malay",
          lang_id: 10022,
        },
        {
          lang_name: "English(USIC)",
          lang_id: 10023,
        },
        {
          lang_name: "English(PSII)",
          lang_id: 10024,
        },
        {
          lang_name: "English(DR)",
          lang_id: 10025,
        },
        {
          lang_name: "English(UK)",
          lang_id: 10026,
        },
        {
          lang_name: "Australia",
          lang_id: 10027,
        },
      ],
      INVENTORY_APPLICABLE: [
        {
          INVENTORY_APPLICABLE: "no",
        },
      ],
    };
    return {
      value: "",
      formSchema,
    };
  },
  mounted: function () {},
  created: function () {
    this.FetchData();
  },
  methods: {
    FetchData: function () {
      var self = this;
      axios
        .get(
          "http://localhost:35924/api/FormLayout?id=&moduleName=CRM&subModuleCode=CRM_LEADS&langCode=en",
          {
            headers: {
              Authorization:
                "bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkEwN0Q4MDM0Rjg3RUMxNTc4MTlEMjUyNTdFN0VERjk0IiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2NTgyOTM1MzEsImV4cCI6MTY1ODMxMTUzMSwiaXNzIjoiaHR0cDovLzE5Mi4xNjguMC4yMDA6OTA5NiIsImF1ZCI6WyJDUk1BUEkiLCJUaWNrZXRpbmciXSwiY2xpZW50X2lkIjoiTVZDSHlicmlkIiwic3ViIjoiNzY5MDgzIiwiYXV0aF90aW1lIjoxNjU4MjkzNTMxLCJpZHAiOiJsb2NhbCIsInByZWZlcnJlZF91c2VybmFtZSI6Ijc2OTA4MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImphbWVzc21pdGhAeW9wbWFpbC5jb20iLCJ1c2VydHlwZSI6IkNBIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IkphbWVzIE9TbWl0aCIsImlzZGVmYXVsdCI6dHJ1ZSwiZ2VuZGVyIjoiIiwiY29tcGFueUlkIjoyNzA5MzYsInRva2VuaWQiOiIiLCJpZCI6NzY5MDgzLCJjb21wYW55TmFtZSI6IkRyaXNoIEluZm8gVGVjaCIsImNvbnRhaW5lck5hbWUiOiJjZy1kcmlzaC1pbmZvLXRlY2gtMjcwOTM2IiwibG9naW5TdGF0dXMiOiIwIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ0EiLCJpc0VuYWJsZUxvZ2luIjoiVHJ1ZSIsImFjdGl2ZUxpY2Vuc2VDb3VudCI6IjEzNyIsIndvcmtpbmdMYW5ndWFnZSI6ImVuIiwidGltZUZvcm1hdCI6IjEyIiwidHJpYWxNZXNzYWdlIjoiIiwiaW5pdGlhbFNldHVwIjoiVHJ1ZSIsImlzU2VhcmNoQmFyT2ZmIjoiRmFsc2UiLCJpc01lbnVTbGlkZXJPZmYiOiJUcnVlIiwiY29tcGFueVN0YXR1c0NvZGUiOiJBQ1QiLCJyZXNldF9QYXNzd29yZCI6IkZhbHNlIiwibWVudXR5cGUiOiJUb3AiLCJ0aW1lem9uZSI6IiswMTowMCIsInRoZW1lIjoiTGlnaHQiLCJjb21wYW55bG9nbyI6ImNvbXBhbnktbG9nby5qcGciLCJhdmF0YXIiOiJIb292ZWZIRExiSUxUUXEucG5nIiwiZGF0ZUZvcm1hdCI6IiIsIklzSW5UcmlhbCI6IkZhbHNlIiwiQ3VycmVuY3kiOiIoVFpTKSIsIlBhZ2VTaXplIjoiMTUiLCJJc1ZlbmRvciI6Im5vIiwiSXNDbGllbnRDQSI6IkNBIiwiVGltZVpvbmVTdGF0dXMiOiJGYWxzZSIsIklzV2l0aENDIjoiVHJ1ZSIsIkRvTm90U2hvd0RpcnR5Q2hlY2siOiJUcnVlIiwiRW5hYmxlTXlEYXNoYm9hcmQiOiJUcnVlIiwiRmxhZ05vdGlmaWNhdGlvbkNoZWNrIjoiRmFsc2UiLCJPcmdDb21hcGFueUlkIjoiMCIsInNpZCI6IjMzMTVFNzc1OTdBRDkwMzY0NUZDREFDRjNBODhENDVDIiwiaWF0IjoxNjU4MjkzNTMxLCJzY29wZSI6WyJvcGVuaWQiLCJwcm9maWxlIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbInB3ZCJdfQ.QuTPdZmgfgWzpxC_OYd1CM6Sx-iNDnCkkzTipUJrTNYElLS1fZSgyAKqz0p2cxGAFI-NaUMjgeccbBJb_Z10E71DC9ioBMGJUapoDA3Hq0pM_6ULOURdz3gChaZzL_SAFqids9inbjOZDGt2ISe7Q5woYEb5YJB3MMEjVIoTIjgqUxJukN6yXOjR5NfbWq1HUp5vPjSY1abg284kqB5K_0PVpAWo0b39jWPy_0yq5eZ9Onzt7DIMJV8ycl3by_x0vlg27yF9FJTtqHYwMRJuLWD7biJsDdUaE8EaKTlWuI0ZLbowzXppft2_J42jiM7xDTjZdibqKk2lpwchaK_TdA",
            },
          }
        )
        .then(function (response) {
          if (response.data != "" && response.data != null) {
            
          }
          console.log(response.data.data);
          self.formSchema = response.data;
        });
    },
    onSubmit: function (meta) {
      alert(meta.valid);
      const { valid } = this.$refs.form.validate();
      console.log(valid);
      this.$refs.form.setFieldTouched("Amount", true);
      this.$refs.form.setFieldTouched("Discount", true);
      //meta.touched = true;
      this.$refs.form.validate();
    },
  },
};
</script>